feat: add customer email to order, fix  order tests, use native funct…
augustin-wien/augustina-backend pull request #142
Opened 2023-12-13 21:54 UTC by nanu-c

…ions in ListPayments and allow empty strings for subpayment.ReceiverName,  Avoid using DB outside the current connection in VerifyOrderAndCreatePayments

# Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Description

This is a first step for the digital license backend customer part. But actually it's fixing a lot of things that have to be solved on the way.

**IMPORTANT TO KNOW**

When i was enabling the order tests again, it took forever, because the requests were blocking themself. So i replaced the calls to the database without a pgx.Tx to one with pgx.Tx and i had to change the get payments, too.

There is still the code missing to create the customer in keycloak, because we don't have the keycloak group the user should be added to for the current newspaper number in order to give access in wordpress. 
Also I think this pr is already quite complex to review so i will solve the other problems with customers in a follow up pr.

**CHANGES**

* add customer email to order and require an email for all license items
* fix order tests, 
* the item creation in the tests had to be appended in order to get a custom name, because the item with a license and the item without had the same name, which doesn't work, when they are used in the same test
* use native functions in ListPayments and 
* allow empty strings for subpayment.ReceiverName,  
* Avoid using DB outside the current connection in VerifyOrderAndCreatePayments -> this maybe fixes our deadlocks

** to think on **
The order code for orders in the tests shouldn't be `0` for all orders. We need a way to distinguish them in order to start parallel/fast tests.

**TODO**

# Checklist:

- [ ] I have commented my code (or ChatGPT did), particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings, neither in my IDE nor in my browser
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-12-14 13:02 UTC, jofmi requested changes

2023-12-14 14:14 UTC, nanu-c commented on app/database/types.go
> +	SenderName   null.String // JOIN from Sender Account
Yes but for the subpayments we don't join the fields, so it's really null

2023-12-14 14:16 UTC, nanu-c commented on app/database/queries.go
Actually we don't want to save the customer emails in the database but only in keycloak and that part is still missing.

2023-12-14 14:17 UTC, jofmi commented on app/database/queries.go
But you did add a database field?

2023-12-14 14:23 UTC, nanu-c commented on app/database/types.go
> +	CustomerEmail     null.String
The frontend is only giving an email, when a licenseItem is in the basket. For me it sounds more reasonable to have a proper null type here instead of an empty string because it brings it's own check with `CustomerEmail.Valid`

2023-12-14 14:26 UTC, jofmi commented on app/handlers/handlers_test.go
> +		  "customerEmail": "test_customer@example.com"
ok!

2023-12-14 14:26 UTC, jofmi commented on app/database/types.go
> +	CustomerEmail     null.String
ok! just have in mind that this could create confusion as there are two different possibilities for this field to be empty ("" and null)

2023-12-14 14:27 UTC, nanu-c commented on app/migrations/004_add_CustomerEmail.sql
> +ALTER TABLE OrderEntry ADD COLUMN CustomerEmail varchar(255);
Good spot, why is the table name so different from the struct name?

2023-12-14 15:01 UTC, nanu-c commented on app/database/queries.go
Yes i did, we need to keep it until the transaction was accepted by vivawallet

2023-12-14 15:02 UTC, nanu-c commented on app/handlers/handlers_test.go
> +		  "customerEmail": "test_customer@example.com"
I have no way to get the order id so it's difficult to get it, except if i do it as the first test, but when parallel tests are using also orders, it gets diffiult again.

2023-12-14 15:03 UTC, nanu-c commented on app/migrations/004_add_CustomerEmail.sql
> +ALTER TABLE OrderEntry ADD COLUMN CustomerEmail varchar(255);
Okey done

2023-12-14 15:04 UTC, nanu-c commented on app/database/types.go
> +	CustomerEmail     null.String
we should still don't trust the frontend and add a proper email validation

2023-12-18 09:11 UTC, jofmi approved these changes

2023-12-18 09:46 UTC, merged